server:
  port: 8080

spring:
  application:
    name: gateway
  main:
    web-application-type: reactive
  cloud:
    gateway:
      default-filters:
        - DedupeResponseHeader=Access-Control-Allow-Origin Access-Control-Allow-Credentials
      globalcors:
        cors-configurations:
          '[/**]':
            allowedOrigins: ${GATEWAY_ALLOWED_ORIGINS}
            allow-credentials: true # JWT 나 쿠키를 사용해 메시지를 보내야 할 경우 true
            allowedHeaders: '*'
            allowedMethods:
              - PUT
              - GET
              - POST
              - DELETE
              - OPTIONS
      routes:
        - id: pickle-pb
          uri: ${GATEWAY_URI_PB}
          predicates:
            - Path=/api/pickle-pb/**
          filters:
            - name: AuthenticationFilter

        - id: pickle-customer
          uri: ${GATEWAY_URI_CUSTOMER}
          predicates:
            - Path=/api/pickle-customer/**
          filters:
            - name: AuthenticationFilter

        - id: pickle-common
          uri: ${GATEWAY_URI_COMMON}
          predicates:
            - Path=/api/pickle-common/**

